example:
  property: "I AM IN THE DEFAULT"
spring:
  jpa:
    database: "H2"
    show-sql: "true"
  database:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
