example.property: "I AM A PROD PROPERTY OVERRIDE"
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"