spring:
  jpa:
    database: H2
    show-sql: true
    open-in-view: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
signing:
  key: 345345fsdfsf5345
