example.property: "I AM IN THE DEFAULT"
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eagle_eye_local
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
